# Generated by Django 5.1.7 on 2025-08-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
